package com.geppetto.surveybuilder.controller;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;




/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class GpBaseController {

	private com.geppetto.surveybuilder.domain.core.GpUser theUser;
	protected final Log logger = LogFactory.getLog(this.getClass());

	public com.geppetto.surveybuilder.domain.core.GpUser getUser(){

		return null;
	}

	public void setUser(com.geppetto.surveybuilder.domain.core.GpUser user){

	}


}