package com.geppetto.surveybuilder.domain.core;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
 */
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "Option")
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(value = "Option", description = "Option")
public class Option {

	@ApiModelProperty(value = "The standard id attribute - System generated", required = true)
	@Id
	@GeneratedValue
	long id;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long question_id;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String answer;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String answer_image;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String answer_type;

	@ApiModelProperty(value = "description", required = true)
	@Column
	Long slider_value;

	@ApiModelProperty(value = "description", required = true)
	@Column
	Long slider_min;

	@ApiModelProperty(value = "description", required = true)
	@Column
	Long slider_max;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getQuestion_id() {
		return question_id;
	}

	public void setQuestion_id(long question_id) {
		this.question_id = question_id;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getAnswer_image() {
		return answer_image;
	}

	public void setAnswer_image(String answer_image) {
		this.answer_image = answer_image;
	}

	public String getAnswer_type() {
		return answer_type;
	}

	public void setAnswer_type(String answer_type) {
		this.answer_type = answer_type;
	}

	public Long getSlider_value() {
		return slider_value;
	}

	public void setSlider_value(Long slider_value) {
		this.slider_value = slider_value;
	}

	public Long getSlider_min() {
		return slider_min;
	}

	public void setSlider_min(Long slider_min) {
		this.slider_min = slider_min;
	}

	public Long getSlider_max() {
		return slider_max;
	}

	public void setSlider_max(Long slider_max) {
		this.slider_max = slider_max;
	}

	@Override
	public String toString() {
		return "Option [id=" + id + ", question_id=" + question_id
				+ ", answer=" + answer + ", answer_image=" + answer_image
				+ ", answer_type=" + answer_type + ", slider_value="
				+ slider_value + ", slider_min=" + slider_min + ", slider_max="
				+ slider_max + "]";
	}

}