package com.geppetto.surveybuilder.domain.core;


/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;


@Entity

@Table(name="Product")

@JsonIgnoreProperties(ignoreUnknown = true)

@ApiModel( value = "Product", description = "represents a product" )

public class Product  {


	@ApiModelProperty( value = "The standard id attribute - System generated", required = true ) 
	@Id 
 	@GeneratedValue
 	long Id;



	@ApiModelProperty( value = "description", required = true ) 
	@Column
 	String Product_name;



	@ApiModelProperty( value = "description", required = true ) 
	@Column
 	String Product_notes;



	@ApiModelProperty( value = "description", required = true ) 
	@Column
 	Long Created_by;



	@ApiModelProperty( value = "description", required = true ) 
	@Column
 	Date Created_date;



	@ApiModelProperty( value = "description", required = true ) 
	@Column
	Long Modified_by;



	@ApiModelProperty( value = "description", required = true ) 
	@Column
 	Date Modified_date;
	
	@ApiModelProperty( value = "description", required = true ) 
	@Column
 	Long client_id;




	public long getClient_id() {
		if (client_id != null) 
		  return client_id.longValue();
		else
		  return -1;
	}


	public void setClient_id(long client_id) {
		this.client_id = client_id;
	}


	public Date getCreated_date() {
		return Created_date;
	}


	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setProduct_name(String Product_name) {
		this.Product_name = Product_name;
	}


	public String getProduct_name() {
		return Product_name;
	}

	public void setProduct_notes(String Product_notes) {
		this.Product_notes = Product_notes;
	}


	public String getProduct_notes() {
		return Product_notes;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		if (Created_by != null) 
		  return Created_by.longValue();
		else
		  return -1;
	}

	

	public void setModified_by(long Modified_by) {
		this.Modified_by = Modified_by;
	}


	public long getModified_by() {
		if (Modified_by != null) 
		  return Modified_by.longValue();
		else
		  return -1;
	}


	public Date getModified_date() {
		return Modified_date;
	}


	public void setModified_date(Date modified_date) {
		Modified_date = modified_date;
	}


	public void setCreated_date(Date created_date) {
		Created_date = created_date;
	}

}