package com.geppetto.surveybuilder.domain.core;


/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.util.ArrayList;



public class Question_Dto  {

	long id;
	String type_name;
	long type_id;
	String title;
	long value = 20;
	
	ArrayList<Option_Dto> answers;
	
	ArrayList<Items_Dto> items;
	
	Options_Dto options;
	
	public long getValue() {
		return value;
	}

	public void setValue(long value) {
		this.value = value;
	}
	
	public Options_Dto getOptions() {
		return options;
	}

	public void setOptions(Options_Dto options) {
		this.options = options;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType_name() {
		return type_name;
	}

	public void setType_name(String type_name) {
		this.type_name = type_name;
	}

	public long getType_id() {
		return type_id;
	}

	public void setType_id(long type_id) {
		this.type_id = type_id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public ArrayList<Option_Dto> getAnswers() {
		return answers;
	}

	public void setAnswers(ArrayList<Option_Dto> answers) {
		this.answers = answers;
	}

	public ArrayList<Items_Dto> getItems() {
		return items;
	}

	public void setItems(ArrayList<Items_Dto> items) {
		this.items = items;
	}

	@Override
	public String toString() {
		return "Question_Dto [id=" + id + ", type_name=" + type_name
				+ ", type_id=" + type_id + ", title=" + title + ", value="
				+ value + ", answers=" + answers + ", items=" + items
				+ ", options=" + options + "]";
	}

	/*public ArrayList<Option_Dto> getOption_dto() {
		return option_dto;
	}

	public void setOption_dto(ArrayList<Option_Dto> option_dto) {
		this.option_dto = option_dto;
	}*/

	/*@Override
	public String toString() {
		return "Question_Dto [id=" + id + ", type_name=" + type_name
				+ ", type_id=" + type_id + ", title=" + title + ", option_dto="
				+ option_dto + "]";
	}*/

	/*public ArrayList<Items_Dto> getItems_dto() {
		return items_dto;
	}

	public void setItems_dto(ArrayList<Items_Dto> items_dto) {
		this.items_dto = items_dto;
	}*/

	/*@Override
	public String toString() {
		return "Question_Dto [id=" + id + ", type_name=" + type_name
				+ ", type_id=" + type_id + ", title=" + title + ", option_dto="
				+ option_dto + ", items_dto=" + items_dto + "]";
	}*/


}