package com.geppetto.surveybuilder.domain.core;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
 */
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "Question")
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(value = "Question", description = "Question")
public class Question {

	@ApiModelProperty(value = "The standard id attribute - System generated", required = true)
	@Id
	@GeneratedValue
	long Id;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String The_question;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Display_type;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Answer_id;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Order_in_survey;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Group_name;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Group_id;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Rank_importance;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Created_by;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Created_date;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Updated_by;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Updated_date;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Survey_id;

	@Transient
	ArrayList<Option> options;

	@Transient
	List<Servey_result> survey_result;
	
	@ApiModelProperty( value = "description", required = true ) 
	@Column
 	long type_id;
	
	
	public long getType_id() {
		return type_id;
	}



	public void setType_id(long type_id) {
		this.type_id = type_id;
	}


	public List<Servey_result> getSurvey_result() {
		return survey_result;
	}

	public void setSurvey_result(List<Servey_result> survey_result) {
		this.survey_result = survey_result;
	}

	public long getId() {
		return Id;
	}

	public void setId(long id) {
		Id = id;
	}

	public String getThe_question() {
		return The_question;
	}

	public void setThe_question(String the_question) {
		The_question = the_question;
	}

	public String getDisplay_type() {
		return Display_type;
	}

	public void setDisplay_type(String display_type) {
		Display_type = display_type;
	}

	public long getAnswer_id() {
		return Answer_id;
	}

	public void setAnswer_id(long answer_id) {
		Answer_id = answer_id;
	}

	public long getOrder_in_survey() {
		return Order_in_survey;
	}

	public void setOrder_in_survey(long order_in_survey) {
		Order_in_survey = order_in_survey;
	}

	public String getGroup_name() {
		return Group_name;
	}

	public void setGroup_name(String group_name) {
		Group_name = group_name;
	}

	public long getGroup_id() {
		return Group_id;
	}

	public void setGroup_id(long group_id) {
		Group_id = group_id;
	}

	public long getRank_importance() {
		return Rank_importance;
	}

	public void setRank_importance(long rank_importance) {
		Rank_importance = rank_importance;
	}

	public long getCreated_by() {
		return Created_by;
	}

	public void setCreated_by(long created_by) {
		Created_by = created_by;
	}

	public long getUpdated_by() {
		return Updated_by;
	}

	public void setUpdated_by(long updated_by) {
		Updated_by = updated_by;
	}

	public long getSurvey_id() {
		return Survey_id;
	}

	public void setSurvey_id(long survey_id) {
		Survey_id = survey_id;
	}



	public String getCreated_date() {
		return Created_date;
	}



	public void setCreated_date(String created_date) {
		Created_date = created_date;
	}



	public String getUpdated_date() {
		return Updated_date;
	}



	public void setUpdated_date(String updated_date) {
		Updated_date = updated_date;
	}



	public ArrayList<Option> getOptions() {
		return options;
	}



	public void setOptions(ArrayList<Option> options) {
		this.options = options;
	}
	
	

}