package com.geppetto.surveybuilder.domain.core;



/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.util.ArrayList;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


@JsonIgnoreProperties(ignoreUnknown = true)
public class Survey_Dto  {


 	long Id;

 	String Survey_name;

 	String Survey_description;

 	String Survey_notes;

 	String Client_name;

 	String Product_name;

 	String Country_name;

	public String status;
	
	long client_id;
	long product_id ;
	long  country_id;

	public long getClient_id() {
		return client_id;
	}


	public void setClient_id(long client_id) {
		this.client_id = client_id;
	}


	public long getProduct_id() {
		return product_id;
	}


	public void setProduct_id(long product_id) {
		this.product_id = product_id;
	}


	public long getCountry_id() {
		return country_id;
	}


	public void setCountry_id(long country_id) {
		this.country_id = country_id;
	}


	ArrayList<Question_Dto> questions;
	
	
	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}



	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setSurvey_name(String Survey_name) {
		this.Survey_name = Survey_name;
	}


	public String getSurvey_name() {
		return Survey_name;
	}

	public void setSurvey_description(String Survey_description) {
		this.Survey_description = Survey_description;
	}


	public String getSurvey_description() {
		return Survey_description;
	}

	public void setSurvey_notes(String Survey_notes) {
		this.Survey_notes = Survey_notes;
	}


	public String getSurvey_notes() {
		return Survey_notes;
	}

	public void setClient_name(String Client_name) {
		this.Client_name = Client_name;
	}


	public String getClient_name() {
		return Client_name;
	}

	public void setProduct_name(String Product_name) {
		this.Product_name = Product_name;
	}


	public String getProduct_name() {
		return Product_name;
	}

	public void setCountry_name(String Country_name) {
		this.Country_name = Country_name;
	}


	public String getCountry_name() {
		return Country_name;
	}


	public ArrayList<Question_Dto> getQuestions() {
		return questions;
	}


	public void setQuestions(ArrayList<Question_Dto> questions) {
		this.questions = questions;
	}


	@Override
	public String toString() {
		return "Survey_Dto [Id=" + Id + ", Survey_name=" + Survey_name
				+ ", Survey_description=" + Survey_description
				+ ", Survey_notes=" + Survey_notes + ", Client_name="
				+ Client_name + ", Product_name=" + Product_name
				+ ", Country_name=" + Country_name + ", status=" + status
				+ ", client_id=" + client_id + ", product_id=" + product_id
				+ ", country_id=" + country_id + ", questions=" + questions
				+ "]";
	}


	/*public ArrayList<Question_Dto> getQuestion_dto() {
		return question_dto;
	}


	public void setQuestion_dto(ArrayList<Question_Dto> question_dto) {
		this.question_dto = question_dto;
	}


	@Override
	public String toString() {
		return "Survey_Dto [Id=" + Id + ", Survey_name=" + Survey_name
				+ ", Survey_description=" + Survey_description
				+ ", Survey_notes=" + Survey_notes + ", Client_name="
				+ Client_name + ", Product_name=" + Product_name
				+ ", Country_name=" + Country_name + ", status=" + status
				+ ", question_dto=" + question_dto + "]";
	}
*/

	

}