package com.geppetto.surveybuilder.domain.core;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
 */
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "Survey")
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(value = "Survey", description = "survey")
public class Survey {

	@ApiModelProperty(value = "The standard id attribute - System generated", required = true)
	@Id
	@GeneratedValue
	long Id;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Survey_name;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Survey_description;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Survey_notes;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Client_name;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Product_name;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Country_name;

	@Transient
	List<Question> Question;

	@ApiModelProperty(value = "description", required = true)
	@Column
	public String status;

	@Transient
	List<Survey> create;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Client_id;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Product_id;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Country_id;
	


	public List<Question> getQuestion() {
		return Question;
	}

	public void setQuestion(List<Question> question) {
		Question = question;
	}

	public long getClient_Id() {
		return Client_id;
	}

	public void setClient_Id(long Client_id) {
		this.Client_id = Client_id;
	}

	public long getProduct_Id() {
		return Product_id;
	}

	public void setProduct_Id(long Product_id) {
		this.Product_id = Product_id;
	}

	public long getCountry_Id() {
		return Country_id;
	}

	public void setCountry_Id(long Country_id) {
		this.Country_id = Country_id;
	}

	public List<Survey> getCreate() {
		return create;
	}

	public void setCreate(List<Survey> create) {
		this.create = create;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/*public List<Question> getQuestion_list() {
		return Question_list;
	}

	public void setQuestion(List<Question> Question_list) {
		this.Question_list = Question_list;
	}
*/
	public void setId(long Id) {
		this.Id = Id;
	}

	public long getId() {
		return Id;
	}

	public void setSurvey_name(String Survey_name) {
		this.Survey_name = Survey_name;
	}

	public String getSurvey_name() {
		return Survey_name;
	}

	public void setSurvey_description(String Survey_description) {
		this.Survey_description = Survey_description;
	}

	public String getSurvey_description() {
		return Survey_description;
	}

	public void setSurvey_notes(String Survey_notes) {
		this.Survey_notes = Survey_notes;
	}

	public String getSurvey_notes() {
		return Survey_notes;
	}

	public void setClient_name(String Client_name) {
		this.Client_name = Client_name;
	}

	public String getClient_name() {
		return Client_name;
	}

	public void setProduct_name(String Product_name) {
		this.Product_name = Product_name;
	}

	public String getProduct_name() {
		return Product_name;
	}

	public void setCountry_name(String Country_name) {
		this.Country_name = Country_name;
	}

	public String getCountry_name() {
		return Country_name;
	}

}